### Obtener todas las solicitudes
GET http://localhost:3000/api/solicitudes


### Crear una solicitud
POST http://localhost:3000/api/solicitudes
Content-Type: application/json

{
  "dniCliente": "0501-2000-12345",
  "nombreCompleto": "Juan Perez",
  "montoSolicitado": 15000,
  "plazoMeses": 12,
  "tasaInteres": 3.5
}